[package]
name = "hotkey"
version = "0.1.0"
edition = "2021"


[dependencies]
once_cell = "1.9.0"
[dependencies.windows]
version = "0.32.0"
features = [
    "Win32_Foundation",
    "Win32_UI_WindowsAndMessaging",
    "Win32_UI_Input_KeyboardAndMouse",
]